export let fakeApiUsers = [
  { id: 1, username: "Avery Johnson", points: 1280 },
  { id: 2, username: "Mia Thompson", points: 1135 },
  { id: 3, username: "Noah Williams", points: 1040 },
  { id: 4, username: "Sophia Brown", points: 970 },
  { id: 5, username: "Liam Davis", points: 890 },
  { id: 6, username: "Emma Miller", points: 760 },
  { id: 7, username: "Lucas Wilson", points: 710 },
  { id: 8, username: "Olivia Moore", points: 650 },
  { id: 9, username: "Ethan Taylor", points: 590 },
  { id: 10, username: "Isabella Anderson", points: 520 },
  { id: 11, username: "James Thomas", points: 500 },
  { id: 12, username: "Charlotte Jackson", points: 470 },
  { id: 13, username: "Benjamin White", points: 450 },
  { id: 14, username: "Amelia Harris", points: 420 },
  { id: 15, username: "Elijah Martin", points: 400 },
  { id: 16, username: "Harper Thompson", points: 380 },
  { id: 17, username: "Alexander Garcia", points: 360 },
  { id: 18, username: "Evelyn Martinez", points: 340 },
  { id: 19, username: "Daniel Robinson", points: 320 },
  { id: 20, username: "Abigail Clark", points: 300 },
  { id: 21, username: "Matthew Rodriguez", points: 280 },
  { id: 22, username: "Emily Lewis", points: 260 },
  { id: 23, username: "Joseph Lee", points: 240 },
  { id: 24, username: "Elizabeth Walker", points: 220 },
  { id: 25, username: "David Hall", points: 200 },
  { id: 26, username: "Sofia Allen", points: 180 },
  { id: 27, username: "Michael Young", points: 160 },
  { id: 28, username: "Avery King", points: 140 },
  { id: 29, username: "William Wright", points: 120 },
  { id: 30, username: "Ella Scott", points: 100 }
];

export let fakeApiEvents = [
  {
    id: 1,
    name: "Welcome Week Kickoff",
    description: "Join us for the biggest event of the semester! Free food, games, and a chance to meet your classmates.",
    clubId: 14,
    date: "Sept 5",
    time: "3:00 PM",
    location: "Main Quad",
    tag: "Popular",
    users: [1, 2, 3, 4, 5],
    stage: 0
  },
  {
    id: 2,
    name: "Photography Walk",
    description: "Explore campus and take photos together.",
    clubId: 1,
    date: "Sept 20",
    time: "4:00 PM",
    location: "Campus Grounds",
    tag: "Creative",
    users: [13, 25],
    stage: 3
  },
  {
    id: 3,
    name: "Yoga in the Park",
    description: "Relax and unwind with a guided yoga session.",
    clubId: 13,
    date: "Sept 8",
    time: "8:00 AM",
    location: "City Park",
    tag: "Health",
    users: [3, 8, 9],
    stage: 2
  },
  {
    id: 4,
    name: "Movie Night",
    description: "Enjoy a classic movie with popcorn and friends.",
    clubId: 12,
    date: "Sept 9",
    time: "8:00 PM",
    location: "Student Center Theater",
    tag: "Social",
    users: [1, 4, 10],
    stage: 3
  },
  {
    id: 5,
    name: "Hackathon 2026",
    description: "24-hour coding competition with prizes.",
    clubId: 2,
    date: "Sept 12",
    time: "10:00 AM",
    location: "Innovation Lab",
    tag: "Popular",
    users: [5, 6, 7, 11],
    stage: 3
  },
  {
    id: 6,
    name: "Art Workshop",
    description: "Learn watercolor techniques from a local artist.",
    clubId: 3,
    date: "Sept 10",
    time: "2:00 PM",
    location: "Art Studio",
    tag: "Creative",
    users: [8, 12],
    stage: 3
  },
  {
    id: 7,
    name: "Basketball Tournament",
    description: "3v3 tournament with prizes for winners.",
    clubId: 4,
    date: "Sept 11",
    time: "1:00 PM",
    location: "Gymnasium",
    tag: "Sports",
    users: [2, 9, 13],
    stage: 3
  },
  {
    id: 8,
    name: "Networking Night",
    description: "Meet professionals and expand your network.",
    clubId: 5,
    date: "Sept 13",
    time: "5:00 PM",
    location: "Conference Hall",
    tag: "Career",
    users: [6, 14, 15],
    stage: 3
  },
  {
    id: 9,
    name: "Book Club Meeting",
    description: "Discuss this month’s book selection.",
    clubId: 6,
    date: "Sept 14",
    time: "4:00 PM",
    location: "Library Room 2",
    tag: "Chill",
    users: [7, 16],
    stage: 3
  },
  {
    id: 10,
    name: "Open Mic Night",
    description: "Showcase your talent—music, poetry, comedy!",
    clubId: 7,
    date: "Sept 15",
    time: "7:00 PM",
    location: "Student Lounge",
    tag: "Fun",
    users: [3, 17, 18],
    stage: 3
  },
  {
    id: 11,
    name: "Volunteer Day",
    description: "Give back to the community with us.",
    clubId: 8,
    date: "Sept 16",
    time: "9:00 AM",
    location: "Downtown Center",
    tag: "Impact",
    users: [4, 19],
    stage: 3
  },
  {
    id: 12,
    name: "Gaming Tournament",
    description: "Compete in popular games and win prizes.",
    clubId: 9,
    date: "Sept 17",
    time: "6:00 PM",
    location: "Esports Arena",
    tag: "Popular",
    users: [10, 20, 21],
    stage: 4
  },
  {
    id: 13,
    name: "Cooking Class",
    description: "Learn to cook quick and healthy meals.",
    clubId: 10,
    date: "Sept 18",
    time: "5:30 PM",
    location: "Kitchen Lab",
    tag: "Food",
    users: [11, 22],
    stage: 3
  },
  {
    id: 14,
    name: "Startup Pitch Night",
    description: "Pitch your startup idea and get feedback.",
    clubId: 11,
    date: "Sept 19",
    time: "6:30 PM",
    location: "Business Center",
    tag: "Career",
    users: [12, 23, 24],
    stage: 3
  }
];

export let fakeApiClubs = [
  { id: 1, name: "Photography Club", users: [1, 4, 10], admins: [1], events: [2] },
  { id: 2, name: "Coding Club", users: [1, 5, 6, 7, 11], admins: [5], events: [5] },
  { id: 3, name: "Art Club", users: [1, 8, 12], admins: [8], events: [6] },
  { id: 4, name: "Sports Club", users: [1, 2, 9, 13], admins: [2], events: [7] },
  { id: 5, name: "Business Club", users: [1, 6, 14, 15], admins: [6], events: [8] },
  { id: 6, name: "Literature Club", users: [1, 7, 16], admins: [7], events: [9] },
  { id: 7, name: "Performing Arts", users: [1, 3, 17, 18], admins: [3], events: [10] },
  { id: 8, name: "Community Service Club", users: [1, 4, 19], admins: [4], events: [11] },
  { id: 9, name: "Gaming Club", users: [10, 20, 21], admins: [10], events: [12] },
  { id: 10, name: "Culinary Club", users: [11, 22], admins: [11], events: [13] },
  { id: 11, name: "Entrepreneur Club", users: [12, 23, 24], admins: [12], events: [14] },
  { id: 12, name: "Film Society", users: [13, 25], admins: [13], events: [4] },
  { id: 13, name: "Wellness Club", users: [14, 26], admins: [14], events: [3] },
  { id: 14, name: "Student Government", users: [15, 27], admins: [15], events: [1] }
];