export const fakeApiUsers = [
  { id: 1, username: "Avery Johnson", points: 1280 },
  { id: 2, username: "Mia Thompson", points: 1135 },
  { id: 3, username: "Noah Williams", points: 1040 },
  { id: 4, username: "Sophia Brown", points: 970 },
  { id: 5, username: "Liam Davis", points: 890 },
  { id: 6, username: "Emma Miller", points: 760 },
  { id: 7, username: "Lucas Wilson", points: 710 },
  { id: 8, username: "Olivia Moore", points: 650 },
  { id: 9, username: "Ethan Taylor", points: 590 },
  { id: 10, username: "Isabella Anderson", points: 520 },
  { id: 11, username: "James Thomas", points: 500 },
  { id: 12, username: "Charlotte Jackson", points: 470 },
  { id: 13, username: "Benjamin White", points: 450 },
  { id: 14, username: "Amelia Harris", points: 420 },
  { id: 15, username: "Elijah Martin", points: 400 },
  { id: 16, username: "Harper Thompson", points: 380 },
  { id: 17, username: "Alexander Garcia", points: 360 },
  { id: 18, username: "Evelyn Martinez", points: 340 },
  { id: 19, username: "Daniel Robinson", points: 320 },
  { id: 20, username: "Abigail Clark", points: 300 },
  { id: 21, username: "Matthew Rodriguez", points: 280 },
  { id: 22, username: "Emily Lewis", points: 260 },
  { id: 23, username: "Joseph Lee", points: 240 },
  { id: 24, username: "Elizabeth Walker", points: 220 },
  { id: 25, username: "David Hall", points: 200 },
  { id: 26, username: "Sofia Allen", points: 180 },
  { id: 27, username: "Michael Young", points: 160 },
  { id: 28, username: "Avery King", points: 140 },
  { id: 29, username: "William Wright", points: 120 },
  { id: 30, username: "Ella Scott", points: 100 }
];

export const fakeApiEvents = [
    {
        id: 1,
        name: "Welcome Week Kickoff",
        description: "Join us for the biggest event of the semester! Free food, games, and a chance to meet your classmates.",
        club: "Student Government",
        date: "Sept 5",
        time: "3:00 PM",
        location: "Main Quad",
        tag: "Popular",
        users: [1, 2, 3, 4, 5]
    },
    {
        id: 2,
        name: "Photography Walk",
        description: "Explore campus and take photos together.",
        club: "Photography Club",
        date: "Sept 20",
        time: "4:00 PM",
        location: "Campus Grounds",
        tag: "Creative",
        users: [13, 25]
    },
    {
        id: 3,
        name: "Yoga in the Park",
        description: "Relax and unwind with a guided yoga session.",
        club: "Wellness Club",
        date: "Sept 8",
        time: "8:00 AM",
        location: "City Park",
        tag: "Health",
        users: [3, 8, 9]
    },
    {
        id: 4,
        name: "Movie Night",
        description: "Enjoy a classic movie with popcorn and friends.",
        club: "Film Society",
        date: "Sept 9",
        time: "8:00 PM",
        location: "Student Center Theater",
        tag: "Social",
        users: [1, 4, 10]
    },
    {
        id: 5,
        name: "Hackathon 2026",
        description: "24-hour coding competition with prizes.",
        club: "Coding Club",
        date: "Sept 12",
        time: "10:00 AM",
        location: "Innovation Lab",
        tag: "Popular",
        users: [5, 6, 7, 11]
    },
    {
        id: 6,
        name: "Art Workshop",
        description: "Learn watercolor techniques from a local artist.",
        club: "Art Club",
        date: "Sept 10",
        time: "2:00 PM",
        location: "Art Studio",
        tag: "Creative",
        users: [8, 12]
    },
    {
        id: 7,
        name: "Basketball Tournament",
        description: "3v3 tournament with prizes for winners.",
        club: "Sports Club",
        date: "Sept 11",
        time: "1:00 PM",
        location: "Gymnasium",
        tag: "Sports",
        users: [2, 9, 13]
    },
    {
        id: 8,
        name: "Networking Night",
        description: "Meet professionals and expand your network.",
        club: "Business Club",
        date: "Sept 13",
        time: "5:00 PM",
        location: "Conference Hall",
        tag: "Career",
        users: [6, 14, 15]
    },
    {
        id: 9,
        name: "Book Club Meeting",
        description: "Discuss this month’s book selection.",
        club: "Literature Club",
        date: "Sept 14",
        time: "4:00 PM",
        location: "Library Room 2",
        tag: "Chill",
        users: [7, 16]
    },
    {
        id: 10,
        name: "Open Mic Night",
        description: "Showcase your talent—music, poetry, comedy!",
        club: "Performing Arts",
        date: "Sept 15",
        time: "7:00 PM",
        location: "Student Lounge",
        tag: "Fun",
        users: [3, 17, 18]
    },
    {
        id: 11,
        name: "Volunteer Day",
        description: "Give back to the community with us.",
        club: "Community Service Club",
        date: "Sept 16",
        time: "9:00 AM",
        location: "Downtown Center",
        tag: "Impact",
        users: [4, 19]
    },
    {
        id: 12,
        name: "Gaming Tournament",
        description: "Compete in popular games and win prizes.",
        club: "Gaming Club",
        date: "Sept 17",
        time: "6:00 PM",
        location: "Esports Arena",
        tag: "Popular",
        users: [10, 20, 21]
    },
    {
        id: 13,
        name: "Cooking Class",
        description: "Learn to cook quick and healthy meals.",
        club: "Culinary Club",
        date: "Sept 18",
        time: "5:30 PM",
        location: "Kitchen Lab",
        tag: "Food",
        users: [11, 22]
    },
    {
        id: 14,
        name: "Startup Pitch Night",
        description: "Pitch your startup idea and get feedback.",
        club: "Entrepreneur Club",
        date: "Sept 19",
        time: "6:30 PM",
        location: "Business Center",
        tag: "Career",
        users: [12, 23, 24]
    }
];

export const fakeApiGroups = [
    { id: 1, name: "Photography Club" },
    { id: 2, name: "Coding Club" },
    { id: 3, name: "Art Club" },
    { id: 4, name: "Sports Club" },
    { id: 5, name: "Business Club" },
    { id: 6, name: "Literature Club" },
    { id: 7, name: "Performing Arts" },
    { id: 8, name: "Community Service Club" },
    { id: 9, name: "Gaming Club" },
    { id: 10, name: "Culinary Club" },
    { id: 11, name: "Entrepreneur Club" },
    { id: 12, name: "Film Society" },
    { id: 13, name: "Wellness Club" },
    { id: 14, name: "Student Government" }
];
