export let fakeApiUsers = [
  { id: 1, username: "Avery Johnson", points: 1280 },
  { id: 2, username: "Mia Thompson", points: 1135, type: "admin" },
  { id: 3, username: "Noah Williams", points: 1040 },
  { id: 4, username: "Sophia Brown", points: 970 },
  { id: 5, username: "Liam Davis", points: 890 },
  { id: 6, username: "Emma Miller", points: 760 },
  { id: 7, username: "Lucas Wilson", points: 710 },
  { id: 8, username: "Olivia Moore", points: 650 },
  { id: 9, username: "Ethan Taylor", points: 590 },
  { id: 10, username: "Isabella Anderson", points: 520 },
  { id: 11, username: "James Thomas", points: 500 },
  { id: 12, username: "Charlotte Jackson", points: 470 },
  { id: 13, username: "Benjamin White", points: 450 },
  { id: 14, username: "Amelia Harris", points: 420 },
  { id: 15, username: "Elijah Martin", points: 400 },
  { id: 16, username: "Harper Thompson", points: 380 },
  { id: 17, username: "Alexander Garcia", points: 360 },
  { id: 18, username: "Evelyn Martinez", points: 340 },
  { id: 19, username: "Daniel Robinson", points: 320 },
  { id: 20, username: "Abigail Clark", points: 300 },
  { id: 21, username: "Matthew Rodriguez", points: 280 },
  { id: 22, username: "Emily Lewis", points: 260 },
  { id: 23, username: "Joseph Lee", points: 240 },
  { id: 24, username: "Elizabeth Walker", points: 220 },
  { id: 25, username: "David Hall", points: 200 },
  { id: 26, username: "Sofia Allen", points: 180 },
  { id: 27, username: "Michael Young", points: 160 },
  { id: 28, username: "Avery King", points: 140 },
  { id: 29, username: "William Wright", points: 120 },
  { id: 30, username: "Ella Scott", points: 100 }
];

export let fakeApiEvents = [
  {
    id: 1,
    name: "Welcome Week Kickoff",
    description: "Biggest event of the semester.",
    location: "Main Quad",
    dateTime: new Date(2026, 8, 5),
    facilities: 2,
    it: 2,
    finance: 2,
    clubId: 14,
    tag: "Popular",
    status: 3,
    users: [1, 2, 3, 4, 5],
  },
  {
    id: 2,
    name: "Photography Walk",
    description: "Explore campus and take photos.",
    location: "Campus Grounds",
    dateTime: new Date(2026, 8, 20),
    facilities: 0,
    it: 0,
    finance: 0,
    clubId: 1,
    tag: "Creative",
    status: 3,
    users: [13, 25],
  },
  {
    id: 3,
    name: "Yoga in the Park",
    description: "Relax and unwind.",
    location: "City Park",
    dateTime: new Date(2026, 8, 8),
    facilities: 1,
    it: 0,
    finance: 0,
    clubId: 13,
    tag: "Health",
    status: 2,
    users: [3, 8, 9],
  },
  {
    id: 4,
    name: "Movie Night",
    description: "Classic movie night.",
    location: "Student Center Theater",
    dateTime: new Date(2026, 8, 9),
    facilities: 2,
    it: 1,
    finance: 0,
    clubId: 12,
    tag: "Social",
    status: 0,
    users: [1, 4, 10],
  },
  {
    id: 5,
    name: "Hackathon 2026",
    description: "24-hour coding competition.",
    location: "Innovation Lab",
    dateTime: new Date(2026, 8, 12),
    facilities: 1,
    it: 2,
    finance: 1,
    clubId: 2,
    tag: "Popular",
    status: 0,
    users: [5, 6, 7, 11],
  },
  {
    id: 6,
    name: "Art Workshop",
    description: "Watercolor techniques.",
    location: "Art Studio",
    dateTime: new Date(2026, 8, 10),
    facilities: 0,
    it: 0,
    finance: 0,
    clubId: 3,
    tag: "Creative",
    status: 3,
    users: [8, 12],
  },
  {
    id: 7,
    name: "Basketball Tournament",
    description: "3v3 tournament.",
    location: "Gymnasium",
    dateTime: new Date(2026, 8, 11),
    facilities: 2,
    it: 0,
    finance: 2,
    clubId: 4,
    tag: "Sports",
    status: 3,
    users: [2, 9, 13],
  },
  {
    id: 8,
    name: "Networking Night",
    description: "Meet professionals.",
    location: "Conference Hall",
    dateTime: new Date(2026, 8, 13),
    facilities: 1,
    it: 1,
    finance: 2,
    clubId: 5,
    tag: "Career",
    status: 0,
    users: [6, 14, 15],
  },
  {
    id: 9,
    name: "Book Club Meeting",
    description: "Monthly discussion.",
    location: "Library Room 2",
    dateTime: new Date(2026, 8, 14),
    facilities: 0,
    it: 0,
    finance: 0,
    clubId: 6,
    tag: "Chill",
    status: 3,
    users: [7, 16],
  },
  {
    id: 10,
    name: "Open Mic Night",
    description: "Talent showcase.",
    location: "Student Lounge",
    dateTime: new Date(2026, 8, 15),
    facilities: 1,
    it: 2,
    finance: 0,
    clubId: 7,
    tag: "Fun",
    status: 3,
    users: [3, 17, 18],
  },
  {
    id: 11,
    name: "Volunteer Day",
    description: "Community service.",
    location: "Downtown Center",
    dateTime: new Date(2026, 8, 16),
    facilities: 2,
    it: 0,
    finance: 0,
    clubId: 8,
    tag: "Impact",
    status: 3,
    users: [4, 19],
  },
  {
    id: 12,
    name: "Gaming Tournament",
    description: "Compete and win.",
    location: "Esports Arena",
    dateTime: new Date(2026, 8, 17),
    facilities: 0,
    it: 2,
    finance: 1,
    clubId: 9,
    tag: "Popular",
    status: 4,
    users: [10, 20, 21],
  },
  {
    id: 13,
    name: "Cooking Class",
    description: "Healthy meals.",
    location: "Kitchen Lab",
    dateTime: new Date(2026, 8, 18),
    facilities: 1,
    it: 0,
    finance: 0,
    clubId: 10,
    tag: "Food",
    status: 0,
    users: [11, 22],
  },
  {
    id: 14,
    name: "Startup Pitch Night",
    description: "Pitch your idea.",
    location: "Business Center",
    dateTime: new Date(2026, 8, 19),
    facilities: 2,
    it: 1,
    finance: 2,
    clubId: 11,
    tag: "Career",
    status: 3,
    users: [12, 23, 24],
  }
];

export let fakeApiClubs = [
  { id: 1, name: "Photography Club", users: [1, 4, 10], admins: [1], events: [2] },
  { id: 2, name: "Coding Club", users: [1, 5, 6, 7, 11], admins: [5], events: [5] },
  { id: 3, name: "Art Club", users: [1, 8, 12], admins: [8], events: [6] },
  { id: 4, name: "Sports Club", users: [1, 2, 9, 13], admins: [2], events: [7] },
  { id: 5, name: "Business Club", users: [1, 6, 14, 15], admins: [6], events: [8] },
  { id: 6, name: "Literature Club", users: [1, 7, 16], admins: [7], events: [9] },
  { id: 7, name: "Performing Arts", users: [1, 3, 17, 18], admins: [3], events: [10] },
  { id: 8, name: "Community Service Club", users: [1, 4, 19], admins: [4], events: [11] },
  { id: 9, name: "Gaming Club", users: [10, 20, 21], admins: [10], events: [12] },
  { id: 10, name: "Culinary Club", users: [11, 22], admins: [11], events: [13] },
  { id: 11, name: "Entrepreneur Club", users: [12, 23, 24], admins: [12], events: [14] },
  { id: 12, name: "Film Society", users: [13, 25], admins: [13], events: [4] },
  { id: 13, name: "Wellness Club", users: [14, 26], admins: [14], events: [3] },
  { id: 14, name: "Student Government", users: [15, 27], admins: [15], events: [1] }
];

export let fakeApiFeedbacks = [
  { userId: 1, eventId: 1, rating: 9, description: "Amazing kickoff event, loved the energy and food!" },
  { userId: 2, eventId: 1, rating: 7, description: "Great turnout, but lines were a bit long." },
  { userId: 3, eventId: 1, rating: 8, description: "Met so many new people, super fun!" },
  { userId: 4, eventId: 4, rating: 7, description: "Movie selection was great, comfy setup." },
  { userId: 10, eventId: 4, rating: 5, description: "Good event, but audio could’ve been better." },
  { userId: 5, eventId: 5, rating: 9, description: "Hackathon was intense and rewarding!" },
  { userId: 6, eventId: 5, rating: 8, description: "Loved collaborating, but needed more snacks." },
  { userId: 7, eventId: 5, rating: 9, description: "Best event so far this semester!" },
  { userId: 11, eventId: 5, rating: 7, description: "Great experience, learned a lot." },
  { userId: 8, eventId: 6, rating: 8, description: "Super relaxing and creative workshop." },
  { userId: 12, eventId: 6, rating: 7, description: "Instructor was awesome, learned new techniques." },
  { userId: 2, eventId: 7, rating: 7, description: "Competitive and fun, well organized." },
  { userId: 9, eventId: 7, rating: 8, description: "Loved the tournament vibe!" },
  { userId: 13, eventId: 7, rating: 6, description: "Fun, but scheduling was a bit off." },
  { userId: 6, eventId: 8, rating: 9, description: "Great networking opportunities!" },
  { userId: 14, eventId: 8, rating: 7, description: "Met some cool professionals." },
  { userId: 15, eventId: 8, rating: 8, description: "Helpful event for career growth." },
  { userId: 7, eventId: 9, rating: 7, description: "Nice chill discussion." },
  { userId: 16, eventId: 9, rating: 8, description: "Loved the book choice this month!" },
  { userId: 3, eventId: 10, rating: 9, description: "So much talent on display!" },
  { userId: 17, eventId: 10, rating: 7, description: "Fun night, great performances." },
  { userId: 18, eventId: 10, rating: 8, description: "Would definitely attend again!" },
  { userId: 4, eventId: 11, rating: 9, description: "Very fulfilling volunteer work." },
  { userId: 19, eventId: 11, rating: 8, description: "Great cause, well organized." },
  { userId: 10, eventId: 12, rating: 9, description: "Gaming tournament was hype!" },
  { userId: 20, eventId: 12, rating: 7, description: "Fun competition, good setup." },
  { userId: 21, eventId: 12, rating: 5, description: "Could use more game variety." },
  { userId: 11, eventId: 13, rating: 8, description: "Loved cooking and tasting everything!" },
  { userId: 22, eventId: 13, rating: 7, description: "Very practical skills learned." },
  { userId: 12, eventId: 14, rating: 9, description: "Pitch night was inspiring!" },
  { userId: 23, eventId: 14, rating: 8, description: "Great feedback from judges." },
  { userId: 24, eventId: 14, rating: 9, description: "Motivated me to pursue my idea!" }
];